### ISSUE TITLE
Visibility of status and navigation icons against light backgrounds

### ISSUE THREAD

**Issue by AlexHCC** [syntaxerror247/godot-android-system-bar-color-changer#1]
Hi! Great addon, nice work!
Now that we can change the system bar color, I was wondering how to also change the theme from light to dark when needed, so that the status and navigation bar icons are visible even against a light/white background? 

Edit: It seems like `system_bar_color_changer.lightStatusBar` and `system_bar_color_changer.lightNavigationBar` have no effect.

Thanks!

**Comment by AlexHCC** [comment]
Found the issue, I need to set the `system_bar_color_changer.lightStatusBar` and `system_bar_color_changer.lightNavigationBar` to light before `calling set_status_bar_color()` and `set_navigation_bar_color()`.

**Comment by syntaxerror247** [comment]
@AlexHCC Yes, you need to set those before calling `set_status_bar_color()` or `set_navigation_bar_color()`
I have updated the instructions as well.

Thanks for using this plugin.
